[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "SEEM"
version = "1.0"
description = "Segment Everything Everywhere All at Once."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
]

dependencies = [
    "json_tricks==3.17.3",
    "nltk==3.8.1",
    "vision-datasets==0.2.2",
    "diffdist==0.1",
    "cityscapesscripts==2.2.2",
    "mup==1.0.0",
    "accelerate==0.23.0",
    "kornia==0.7.0",
    "deepspeed==0.10.3",
    "infinibatch==0.1.1",
    "openai-whisper"
]

[tool.poetry.dependencies]
detectron2 = {git = "https://github.com/MaureenZOU/detectron2-xyz.git"}


[project.urls]
"Paper" = "https://arxiv.org/abs/2304.06718"
"Code" = "https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/tree/v1.0"
"Bug Tracker" = "https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/issues"

[tool.setuptools.packages.find]
exclude = ["assets*"]

[tool.wheel]
exclude = ["assets*"]
